name: resources
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo/Vector.png
    - lib/assets/icons/more.png
    - lib/assets/icons/Frame.png
    - lib/assets/icons/share.png
    - lib/assets/images/news1.jpg
