// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBhnIfLhm_0SUKpMFq7B4PVhPvgyXZiAE',
    appId: '1:872460901191:web:1f0528881e979d0631ca62',
    messagingSenderId: '872460901191',
    projectId: 'lets-chat-3da11',
    authDomain: 'lets-chat-3da11.firebaseapp.com',
    storageBucket: 'lets-chat-3da11.appspot.com',
    measurementId: 'G-LP465J1Z8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo2WInBMIomafOfjaNzQzhJjlTuW7VBSs',
    appId: '1:872460901191:android:8cf859f215e50b6431ca62',
    messagingSenderId: '872460901191',
    projectId: 'lets-chat-3da11',
    storageBucket: 'lets-chat-3da11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj9SUCOGTYhXThhAUfSaFdBE4xDmrdGzA',
    appId: '1:872460901191:ios:4abd7f61093dd91831ca62',
    messagingSenderId: '872460901191',
    projectId: 'lets-chat-3da11',
    storageBucket: 'lets-chat-3da11.appspot.com',
    iosBundleId: 'com.example.letsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj9SUCOGTYhXThhAUfSaFdBE4xDmrdGzA',
    appId: '1:872460901191:ios:4abd7f61093dd91831ca62',
    messagingSenderId: '872460901191',
    projectId: 'lets-chat-3da11',
    storageBucket: 'lets-chat-3da11.appspot.com',
    iosBundleId: 'com.example.letsChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBhnIfLhm_0SUKpMFq7B4PVhPvgyXZiAE',
    appId: '1:872460901191:web:5c64bfe5270992e331ca62',
    messagingSenderId: '872460901191',
    projectId: 'lets-chat-3da11',
    authDomain: 'lets-chat-3da11.firebaseapp.com',
    storageBucket: 'lets-chat-3da11.appspot.com',
    measurementId: 'G-DZE4BQ5YFH',
  );
}
