// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSRVMEDVdFhIKFPMyuWzzkQ-eZODtrRoY',
    appId: '1:897933754185:web:1f6e96b2d95da4af432498',
    messagingSenderId: '897933754185',
    projectId: 'chat-app-eb7b8',
    authDomain: 'chat-app-eb7b8.firebaseapp.com',
    storageBucket: 'chat-app-eb7b8.appspot.com',
    measurementId: 'G-KVW15SM2L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_dntNlgfd_ZXqZDL1ENgVBc7eFsy9T0',
    appId: '1:897933754185:android:119262b15986f3a2432498',
    messagingSenderId: '897933754185',
    projectId: 'chat-app-eb7b8',
    storageBucket: 'chat-app-eb7b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClycpXUpQpnnY77lCeUD5PRd-62o0bCqA',
    appId: '1:897933754185:ios:e9fcf72a978edf31432498',
    messagingSenderId: '897933754185',
    projectId: 'chat-app-eb7b8',
    storageBucket: 'chat-app-eb7b8.appspot.com',
    iosBundleId: 'com.example.letsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClycpXUpQpnnY77lCeUD5PRd-62o0bCqA',
    appId: '1:897933754185:ios:e9fcf72a978edf31432498',
    messagingSenderId: '897933754185',
    projectId: 'chat-app-eb7b8',
    storageBucket: 'chat-app-eb7b8.appspot.com',
    iosBundleId: 'com.example.letsChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSRVMEDVdFhIKFPMyuWzzkQ-eZODtrRoY',
    appId: '1:897933754185:web:487ac43e47e1a96f432498',
    messagingSenderId: '897933754185',
    projectId: 'chat-app-eb7b8',
    authDomain: 'chat-app-eb7b8.firebaseapp.com',
    storageBucket: 'chat-app-eb7b8.appspot.com',
    measurementId: 'G-ZXLGT6Q1L8',
  );

}