name: components
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  animated_snack_bar: ^0.4.0
  awesome_dialog: ^3.2.1
  core: any
  resources: any
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0
